ToDoList/Models/ToDo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace ToDoList.Models
{
    public class ToDo
    {
        public int Id { get; set; }
        [DisplayName("Tasks")]
        public string Description { get; set; }
        public bool IsDone { get; set; }
        public virtual ApplicationUser User { get; set; }
    }
}

ToDoList/Controllers/ToDosController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ToDoList.Models;

namespace ToDoList.Controllers
{
    public class ToDosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        public ActionResult Index()
        {
        
            return View();
        }
        private IEnumerable<ToDo> GetMyToDos()
        {

            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);
            IEnumerable<ToDo> TasksList = db.ToDos.ToList().Where(x => x.User == currentUser); 
            int countCompleted = 0;
            foreach(ToDo task in TasksList)
            {
                if (task.IsDone) {
                    countCompleted++;
                }
                
            }

            int todosCount = TasksList.Count();
            if (todosCount == 0) ViewBag.Percent = 0;
            else ViewBag.Percent = Math.Round(100f * ((float)countCompleted / todosCount));
            return TasksList;

        }
        public ActionResult BuildToDoTable()
        {
            return PartialView("_ToDoTablePartial", GetMyToDos());
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateToDo([Bind(Include = "Id,Description")] ToDo toDo)
        {
            if (ModelState.IsValid)
            {
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault(
                   x => x.Id == currentUserId
                 );
                toDo.User = currentUser;
                toDo.IsDone = false;
                db.ToDos.Add(toDo);
                db.SaveChanges();
                
            }

            return PartialView("_ToDoTablePartial", GetMyToDos());
        }
        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDos.Find(id);

            if (toDo == null)
            {
                return HttpNotFound();
            }
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(
               x => x.Id == currentUserId
             );
            if(toDo.User !=currentUser)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            return View(toDo);
        }

        [HttpPost]
        public ActionResult EditToDo(int? id,bool value)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDos.Find(id);
            if (toDo == null)
            {
                return HttpNotFound();
            }
            else
            {
                toDo.IsDone = value;
                db.Entry(toDo).State = EntityState.Modified;
                db.SaveChanges();
            }
            return PartialView("_ToDoTablePartial", GetMyToDos());
        }


      
        [HttpPost]
        public ActionResult Delete(int id)
        {
            ToDo toDo = db.ToDos.Where(x => x.Id == id).FirstOrDefault();
            db.ToDos.Remove(toDo);
            db.SaveChanges();
            return PartialView("_ToDoTablePartial", GetMyToDos());
          
        }

     

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ToDoList/Views/ToDos/Create.cshtml
@model ToDoList.Models.ToDo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ToDo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDone)
                    @Html.ValidationMessageFor(model => model.IsDone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToDoList/Views/ToDos/Delete.cshtml
@model ToDoList.Models.ToDo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ToDo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDone)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ToDoList/Views/ToDos/Details.cshtml
@model ToDoList.Models.ToDo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ToDo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDone)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ToDoList/Views/ToDos/Edit.cshtml
@model ToDoList.Models.ToDo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ToDo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDone)
                    @Html.ValidationMessageFor(model => model.IsDone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToDoList/Views/ToDos/Index.cshtml
@model ToDoList.Models.ToDo

@{
    ViewBag.Title = "Index";
}

<div id="AddToDoForm">
    @using (Ajax.BeginForm("CreateToDo", "ToDos",
 new AjaxOptions { InsertionMode = InsertionMode.Replace, HttpMethod = "POST", UpdateTargetId = "tableDiv" }))
    {
        <div class="form-group">
            @Html.AntiForgeryToken()
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
    }
</div>
<br />
<br />

<div id="tableDiv"></div>

@section Scripts
    {
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/MyScripts/BuildTable.js"></script>
   
    @Scripts.Render("~/bundles/jqueryval")
}
  
    

ToDoList/Views/ToDos/_ToDoTablePartial.cshtml
@model IEnumerable<ToDoList.Models.ToDo>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

<div id="progressToDo">
    <p> @(ViewBag.Percent)%</p>
    <div class="progress">
        <div class="progress-bar" role="progressbar" style="width:@(Html.AttributeEncode(ViewBag.Percent))%">
        </div>
    </div>
</div>
<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>

                @Html.CheckBoxFor(modelItem => item.IsDone, new { id = item.Id, @class = "IsChecked" })

            </td>
            <td>
                @if (!item.IsDone)
                {
                    @Html.DisplayFor(modelItem => item.Description)

                }
                else
                {

                    <div class="CompletedTasks">@Html.DisplayFor(modelItem => item.Description) </div>
                }
            </td>

            <td>


                <a href="" data-id="@item.Id" class="jsDeleteTask"><i class="fa fa-trash"></i></a>
            </td>
        </tr>
    }

</table>
<script src="~/MyScripts/CheckBoxListener.js"></script>
<script>
    $(document).ready(
        function () {
    $(".jsDeleteTask").click(function () {
        var id = $(this).data("id");
        debugger;
        $.ajax({
            url: "/ToDos/Delete/" + id,
            type: "Post"
     

        });

    });

        });
            
</script>